backend = "xrender";

vsync = true;

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 8;

shadow = false;

inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;

corner-radius = 0;
